waitfor(msgbox({'Please arrange your data in a .mat file containing ' ...
'- voxel x time data in ''X'', ' ...
'- mask index in ''indx'', '...
'- optional paradigm in ''pa'' '},'Data Information'));