% =========================================================================
% close all; clear all; clc;
warning('off','all');
global h_main ica st


set(0,'defaulttextinterpreter','latex')
set(0, 'defaultAxesTickLabelInterpreter','latex');
set(0, 'defaultLegendInterpreter','latex');

% Setup ica structure as main variable:
ica = struct('TR',[],'S',[],'Structural',[]);

% Design main window:
h_main.gui = figure('units','normalized',...
    'Position',[0.01 0.05 .20 .9],...
    'Color',[.8 .8 .8],...
    'menubar','none',...
    'name', 'GPICA');

h_main.settings.panel = uipanel('units', 'normalized',...
    'Position', [.05 .48 .9 .5],...
    'BackgroundColor',[.8 .8 .8],...
    'Title','Settings');

h_main.settings.panelext = uipanel('units', 'normalized',...
    'Position', [.05 .35 .9 .12],...
    'BackgroundColor',[.8 .8 .8],...
    'Title','Extensions');


h_main.settings.load = uicontrol('style', 'pushbutton',...
    'parent', h_main.settings.panel,...
    'units', 'normalized',...
    'position', [.1 .85 .8 .12],...
    'string', 'Select data',...
    'CallBack','ica.FileNames = spm_select(Inf,''any'');',...
'CallBack',['createDataPopupMessage;'...
'ica.FileNames = spm_select(Inf,''any'');'...
    'ica.TR = inputdlg(''Set Repetition Time [s]:'');'...
    'evalTRemean;'...
    'ica.Lsize = inputdlg(''Set voxel dimension in format: [l1,l2,l3] (l3 optional):'');']);

% =========================================================================
h_main.settings.ica.algorithm.mtext = uicontrol('style', 'text',...
    'parent', h_main.settings.panel,...
    'units', 'normalized',...
    'position', [.1 .67 .5 .1],...
    'string', 'Number of sources',...
    'Enable','on',...
    'HorizontalAlignment','left',...    
    'BackgroundColor',[.8 .8 .8],...
    'tooltipstring','Set settings');
h_main.settings.ica.algorithm.m = uicontrol('style', 'edit',...
    'parent', h_main.settings.panel,...
    'units', 'normalized',...
    'position', [.6 .72 .2 .05],...
    'string', '6',...
    'Enable','on',...
    'tooltipstring','Set number of sources');

h_main.settings.ica.algorithm.skiptext = uicontrol('style', 'text',...
    'parent', h_main.settings.panel,...
    'units', 'normalized',...
    'position', [.1 .6 .5 .1],...
    'string', 'Warp-up length',...
    'Enable','on',...
    'HorizontalAlignment','left',...    
    'BackgroundColor',[.8 .8 .8],...
    'tooltipstring','Set settings');
h_main.settings.ica.algorithm.skip = uicontrol('style', 'edit',...
    'parent', h_main.settings.panel,...
    'units', 'normalized',...
    'position', [.6 .65 .2 .05],...
    'string', '100',...
    'Enable','on',...
    'tooltipstring','Set number of samples to skip');

h_main.settings.ica.algorithm.nsamplestext = uicontrol('style', 'text',...
    'parent', h_main.settings.panel,...
    'units', 'normalized',...
    'position', [.1 .53 .5 .1],...
    'string', 'Number of samples',...
    'Enable','on',...
    'HorizontalAlignment','left',...    
    'BackgroundColor',[.8 .8 .8],...
    'tooltipstring','Set settings');
h_main.settings.ica.algorithm.nsamples = uicontrol('style', 'edit',...
    'parent', h_main.settings.panel,...
    'units', 'normalized',...
    'position', [.6 .58 .2 .05],...
    'string', '100',...
    'Enable','on',...
    'tooltipstring','Set number of samples');

% =========================================================================
h_main.settings.ica.check = uicontrol('style', 'checkbox',...
    'parent', h_main.settings.panel,...
    'units', 'normalized',...
    'position', [.1 .45 .8 .1],...
    'string', '   Default settings',...
    'BackgroundColor',[.8 .8 .8],...
    'value',1,...
    'CallBack','defaultsetonoff',...
    'tooltipstring','Check to change the default settings');

%% ess / proposal variance
h_main.settings.ica.algorithm.esstext = annotation(h_main.settings.panel,...
    'textbox',...
    'EdgeColor','none',...
   'string', '$\sigma$',...
   'position', [.3 .41 .30 .05],...
   'Interpreter','latex');
h_main.settings.ica.algorithm.ess = uicontrol('style', 'edit',...
    'parent', h_main.settings.panel,...
    'units', 'normalized',...
    'position', [.6 .41 .2 .05],...
    'string', '8e-5',...
    'Enable','off',...
    'tooltipstring','Set variance of proposal distribution');

%% ts og tr / shape and rate for alpha
h_main.settings.ica.algorithm.tstext = annotation(h_main.settings.panel,...
    'textbox',...
    'EdgeColor','none',...
   'string', '$s_b$',...
   'position', [.3 .35 .30 .05],...
   'Interpreter','latex');
h_main.settings.ica.algorithm.ts = uicontrol('style', 'edit',...
    'parent', h_main.settings.panel,...
    'units', 'normalized',...
    'position', [.6 .35 .2 .05],...
    'string', '2',...
    'Enable','off',...
    'tooltipstring','Set shape for alpha prior');

h_main.settings.ica.algorithm.trtext = annotation(h_main.settings.panel,...
    'textbox',...
    'EdgeColor','none',...
   'string', '$r_b$',...
   'position', [.3 .29 .30 .05],...
   'Interpreter','latex');
h_main.settings.ica.algorithm.tr = uicontrol('style', 'edit',...
    'parent', h_main.settings.panel,...
    'units', 'normalized',...
    'position', [.6 .29 .2 .05],...
    'string', '1',...
    'Enable','off',...
    'tooltipstring','Set rate for alpha prior');

%% ss og sr / prior for Psi 
h_main.settings.ica.algorithm.sstext = annotation(h_main.settings.panel,...
    'textbox',...
    'EdgeColor','none',...
   'string', '$s_a$',...
   'position', [.3 .23 .30 .05],...
   'Interpreter','latex');
h_main.settings.ica.algorithm.ss = uicontrol('style', 'edit',...
    'parent', h_main.settings.panel,...
    'units', 'normalized',...
    'position', [.6 .23 .2 .05],...
    'string', '1',...
    'Enable','off',...
    'tooltipstring','Set shape for Psi prior');


h_main.settings.ica.algorithm.srtext = annotation(h_main.settings.panel,...
    'textbox',...
    'EdgeColor','none',...
   'string', '$r_a$',...
   'position', [.3 .17 .30 .05],...
   'Interpreter','latex');
h_main.settings.ica.algorithm.sr = uicontrol('style', 'edit',...
    'parent', h_main.settings.panel,...
    'units', 'normalized',...
    'position', [.6 .17 .2 .05],...
    'string', '1',...
    'Enable','off',...
    'tooltipstring','Set rate for Psi prior');


%% es er / prior for ell
h_main.settings.ica.algorithm.estext = annotation(h_main.settings.panel,...
    'textbox',...
    'EdgeColor','none',...
   'string', 'Temporal dependency [s]',...
   'position', [.05 .11 .7 .05],...
   'Interpreter','latex');
h_main.settings.ica.algorithm.emean = uicontrol('style', 'edit',...
    'parent', h_main.settings.panel,...
    'units', 'normalized',...
    'position', [.6 .11 .2 .05],...
    'string', '0.4',...
    'Enable','off',...
    'tooltipstring','Set ell mean in [s]');


%% es er / prior for ell
h_main.settings.ica.algorithm.stdtext = annotation(h_main.settings.panel,...
    'textbox',...
    'EdgeColor','none',...
   'string', 'Std data 1:yes 0:no',...
   'position', [.05 .05 .7 .05],...
   'Interpreter','latex');
h_main.settings.ica.algorithm.std = uicontrol('style', 'edit',...
    'parent', h_main.settings.panel,...
    'units', 'normalized',...
    'position', [.6 .05 .2 .05],...
    'string', '1',...
    'Enable','off',...
    'tooltipstring','Standalize data');

% h_main.settings.ica.algorithm.ertext = annotation(h_main.settings.panel,...
%     'textbox',...
%     'EdgeColor','none',...
%    'string', '$r_e$',...
%    'position', [.3 .05 .30 .05],...
%    'Interpreter','latex');
% h_main.settings.ica.algorithm.er = uicontrol('style', 'edit',...
%     'parent', h_main.settings.panel,...
%     'units', 'normalized',...
%     'position', [.6 .05 .2 .05],...
%     'string', '1000',...
%     'Enable','off',...
%     'tooltipstring','Set rate for ell prior');


% =========================================================================
h_main.settings.ica.checkconv = uicontrol('style', 'checkbox',...
    'parent', h_main.settings.panelext,...
    'units', 'normalized',...
    'position', [.1 .7 .8 .2],...
    'string', '   Convulutive Extension',...
    'BackgroundColor',[.8 .8 .8],...
    'value',0,...
    'CallBack','defaultsetonoffCONV',...
    'tooltipstring','Check to perform conv extension');

h_main.settings.ica.algorithm.convlagstext = annotation(h_main.settings.panelext,...
    'textbox',...
    'EdgeColor','none',...
   'string', 'Lags',...
   'position', [.05 .6 .7 .01]);
h_main.settings.ica.algorithm.convlags = uicontrol('style', 'edit',...
    'parent', h_main.settings.panelext,...
    'units', 'normalized',...
    'position', [.6 .5 .2 .4],...
    'string', '4',...
    'Enable','off',...
    'tooltipstring','Set number of lags - note long prepossing time');



% =========================================================================
st.fig = [];
h_main.run = uicontrol('style', 'pushbutton',...
    'units', 'normalized',...
    'Position', [.1 .27 .8 .05],...
    'String', 'Perform GPICA',...
    'CallBack','gpica_runfromgui');

h_main.save.analysis = uicontrol('style', 'pushbutton',...
    'units', 'normalized',...
    'Position', [.1 .20 .8 .05],...
    'String', 'Save analysis',...
    'CallBack','uisavev73(''ica'',ica.prs.filename)'); %%

h_main.settings.status.panel = uipanel('units', 'normalized',...
    'Position', [.05 .11 .9 .07],...
    'BackgroundColor',[.8 .8 .8],...
    'Title','Status');

h_main.settings.status.text = uicontrol('style', 'text',...
    'units', 'normalized',...
    'position', [0.1 .13 .8 .02],...
    'string', 'Ready...',...
    'HorizontalAlignment','left',...    
    'BackgroundColor',[.8 .8 .8],...
    'tooltipstring','Status bar');


h_main.quit = uicontrol('style', 'pushbutton',...
    'units', 'normalized',...
    'Position', [.1 .02 .3 .05],...
    'String', 'Quit',...
    'CallBack','close');

h_main.restart = uicontrol('style', 'pushbutton',...
    'units', 'normalized',...
    'Position', [.6 .02 .3 .05],...
    'String', 'Restart',...
    'CallBack','return, close all, clear all, Kalica');