
global h_main ica st

% Setup main figure:
fig = figure('units','normalized',...
    'Position',[0.23 0.05 .7 .9],...
    'menubar','none',...
    'name', 'ICA simulation');
bb      = [];
st      = struct('n', 0, 'vols',[], 'bb',bb,'Space',eye(4),...
    'centre',[0 0 0],'callback','xyz_pos','xhairs',1,'hld',1,'fig',fig,...
    'mode',1,'plugins',[],'snap',[]);
st.vols = cell(24,1);
st.prevmask = [0 0 0];

st.h.orthviews = spm_orthviews('Image',ica.StructuralHeader,[.05 .45 .48 .55]);
spm_orthviews('Space')
colormap gray
drawnow

% Declare panel for cross-hair position.
% st.h.pos.panel = uipanel('units','normalized',...
%     'Position',[0.28 0.57 .235 .14],...
%     'BackgroundColor',[.8 .8 .8],...
%     'Title','Crosshair position [mm]');
% annotation(st.fig,'textbox','String','Coronal','EdgeColor','none',...
%     'Position',[0.3 0.66 0.09052 0.03221]);
% annotation(st.fig,'textbox','String','Sagittal','EdgeColor','none',...
%     'Position',[0.3 0.625 0.09052 0.03221]);
% annotation(st.fig,'textbox','String','Axial','EdgeColor','none',...
%     'Position',[0.3 0.59 0.09052 0.03221]);
% st.h.pos.coronal = uicontrol('style', 'edit',...
%     'parent', st.h.pos.panel,...
%     'units', 'normalized',...
%     'position', [.5 .73 .3 .25],...
%     'string', num2str(st.centre(2),3),...
%     'callback', 'xyz_pos');
% st.h.pos.sagittal = uicontrol('style', 'edit',...
%     'parent', st.h.pos.panel,...
%     'units', 'normalized',...
%     'position', [.5 .43 .3 .25],...
%     'string', num2str(st.centre(1),3),...
%     'callback', 'xyz_pos');
% st.h.pos.horizontal = uicontrol('style', 'edit',...
%     'parent', st.h.pos.panel,...
%     'units', 'normalized',...
%     'position', [.5 .13 .3 .25],...
%     'string', num2str(st.centre(3),3),...
%     'callback', 'xyz_pos');

% Declare panel for active independent component:
st.h.ic.panel = uipanel('units','normalized',...
    'Position',[0.28 0.42 .235 .14],...
    'BackgroundColor',[.8 .8 .8],...
    'Title','IC component display');
st.h.ic.numberICs = annotation(st.fig,'textbox','String',['Number of ICs: ' num2str(ica.ICs)],...
    'EdgeColor', 'none', 'Position',[.3 .51 .3 .03221]);
annotation(st.fig,'textbox','String','Show no.: ',...
    'EdgeColor', 'none', 'Position',[.3 .475 .3 .03221]);
st.h.ic.component = uicontrol('style', 'edit',...
    'parent', st.h.ic.panel,...
    'units', 'normalized',...
    'position', [.5 .45 .3 .25],...
    'string', '1',...
    'callback', 'icashow');
st.h.ic.previous = uicontrol('style', 'pushbutton',...
    'parent', st.h.ic.panel,...
    'units', 'normalized',...
    'position', [.1 .1 .3 .25],...
    'string', 'Previous',...
    'callback', 'icashow');
st.h.ic.next = uicontrol('style', 'pushbutton',...
    'parent', st.h.ic.panel,...
    'units', 'normalized',...
    'position', [.5 .1 .3 .25],...
    'string', 'Next',...
    'callback', 'icashow');

% Declare panel for change of persentage visualization of IC:
st.h.ic.visible.panel = uipanel('units','normalized',...
    'Position',[0.55 0.835 .38 .1],...
    'BackgroundColor',[.8 .8 .8],...
    'Title','Component visibility');
st.h.ic.visible.slide = uicontrol('style', 'slide',...
    'parent', st.h.ic.visible.panel,...
    'Max',5,'Min',0,...
    'Value',1,...
    'units', 'normalized',...
    'position', [.55 .4 .38 .4],...
    'callback', ['ica.ICsvisibility = get(st.h.ic.visible.slide,''Value'');', ...
    'set(st.h.ic.visible.red.text,''String'',[''Maximum ''', ...
    ' num2str(ica.ICsvisibility, 2) '' %'']); set(st.h.ic.visible.blue.text,', ...
    '''String'',[''Minimum '' num2str(ica.ICsvisibility,2) '' %'']); icashow']);
ica.ICsvisibility = get(st.h.ic.visible.slide,'Value'); % Extract number of ICs
uicontrol('Style','text',...
    'parent', st.h.ic.visible.panel,...
    'String',[num2str(get(st.h.ic.visible.slide,'Min')) ' %'],...
    'Units', 'normalized',...
    'BackgroundColor',[.8 .8 .8],...
    'Position',[0.48 0.35 0.07 0.4],...
    'HorizontalAlignment','left');
uicontrol('Style','text',...
    'parent', st.h.ic.visible.panel,...
    'String',[num2str(get(st.h.ic.visible.slide,'Max')) ' %'],...
    'Units', 'normalized',...
    'BackgroundColor',[.8 .8 .8],...
    'Position',[0.94 0.35 0.06 0.4],...
    'HorizontalAlignment','left');
st.h.ic.visible.red.box = uicontrol('Style','text',...
    'parent', st.h.ic.visible.panel,...
    'Units', 'normalized',...
    'BackgroundColor',[1 0 0],...
    'Position',[0.05 0.6 0.1 0.3],...
    'HorizontalAlignment','left');
st.h.ic.visible.red.text = uicontrol('Style','text',...
    'parent', st.h.ic.visible.panel,...
    'String',['Maximum ' num2str(get(st.h.ic.visible.slide,'Value'),2) ' %'],...
    'Units', 'normalized',...
    'BackgroundColor',[.8 .8 .8],...
    'Position',[0.2 0.6 0.25 0.3],...
    'HorizontalAlignment','left');
st.h.ic.visible.blue.box = uicontrol('Style','text',...
    'parent', st.h.ic.visible.panel,...
    'Units', 'normalized',...
    'BackgroundColor',[0 0 1],...
    'Position',[0.05 0.2 0.1 0.3]);
st.h.ic.visible.blue.text = uicontrol('Style','text',...
    'parent', st.h.ic.visible.panel,...
    'String',['Minimum ' num2str(get(st.h.ic.visible.slide,'Value'),2) ' %'],...
    'Units', 'normalized',...
    'BackgroundColor',[.8 .8 .8],...
    'Position',[0.2 0.2 0.35 0.3],...
    'HorizontalAlignment','left');

% Setup model parameters and time series plot area:
st.h.timeplot.axes = axes('units','normalized',...
    'Position',[.3 .07 .63 .3]); % [left, bottom, width, height]
axis tight
st.h.spatial.panel = uibuttongroup('units','normalized',...
    'Position',[.063 .07 .21 .31],...
    'BackgroundColor',[.8 .8 .8],...
    'Title','Model specification');
st.h.spatial.IC.text = uicontrol('Style','Text',...
    'parent', st.h.spatial.panel,...
    'units', 'normalized',...
    'position', [.075 .85 0.8 .1],...
    'BackgroundColor',[.8 .8 .8],...
    'FontSize',10,'FontName','Helvetica','FontWeight','demi',...
    'HorizontalAlignment','left',...
    'String','BOLD response ICs: ');
st.h.spatial.IC = uicontrol('Style','edit',...
    'parent', st.h.spatial.panel,...
    'units', 'normalized',...
    'position', [.5 .75 0.35 .1],...
    'String',num2str(ica.ActiveComp.no'),...
    'Enable','on',...
    'CallBack','newModel');
% st.h.spatial.center = uicontrol('Style','listbox',...
%     'parent', st.h.spatial.panel,...
%     'units', 'normalized',...
%     'position', [.075 .6 .8 .1],...
%     'String',num2str(ica.ActiveComp.no'),...
%     'Enable','on',...
%     'CallBack','newModel');
st.h.spatial.text = uicontrol('Style','Text',...
    'parent', st.h.spatial.panel,...
    'units', 'normalized',...
    'position', [.075 .48 .8 .1],...
    'BackgroundColor',[.8 .8 .8],...
    'FontSize',10,'FontName','Helvetica','FontWeight','demi',...
    'HorizontalAlignment','left',...
    'String','Spatial spread [mm]');
st.h.spatial.coronal.text = uicontrol('Style','Text',...
    'parent', st.h.spatial.panel,...
    'units', 'normalized',...
    'position', [.075 .36 .35 .1],...
    'BackgroundColor',[.8 .8 .8],...
    'FontSize',10,'FontName','Helvetica','FontWeight','demi',...
    'HorizontalAlignment','left',...
    'String','Coronal');
st.h.spatial.coronal = uicontrol('style', 'edit',...
    'parent', st.h.spatial.panel,...
    'units', 'normalized',...
    'position', [.5 .36 .35 .1],...
    'String',5,...
    'Enable','on',...
    'CallBack','icashow;');
st.h.spatial.sagital.text = uicontrol('Style','Text',...
    'parent', st.h.spatial.panel,...
    'units', 'normalized',...
    'position', [.075 .23 .35 .1],...
    'BackgroundColor',[.8 .8 .8],...
    'FontSize',10,'FontName','Helvetica','FontWeight','demi',...
    'HorizontalAlignment','left',...
    'String','Sagital');
st.h.spatial.sagital = uicontrol('style', 'edit',...
    'parent', st.h.spatial.panel,...
    'units', 'normalized',...
    'position', [.5 .23 .35 .1],...
    'String',15,...
    'Enable','on',...
    'CallBack','icashow;');
st.h.spatial.axial.text = uicontrol('Style','Text',...
    'parent', st.h.spatial.panel,...
    'units', 'normalized',...
    'position', [.075 .1 .35 .1],...
    'BackgroundColor',[.8 .8 .8],...
    'FontSize',10,'FontName','Helvetica','FontWeight','demi',...
    'HorizontalAlignment','left',...
    'String','Axial');
st.h.spatial.axial = uicontrol('style', 'edit',...
    'parent', st.h.spatial.panel,...
    'units', 'normalized',...
    'position', [.5 .1 .35 .1],...
    'String',10,...
    'Enable','on',...
    'CallBack','icashow');

% Setup component frequenzy plot area:
st.h.freqplot.axes = axes('units','normalized',...
    'Position',[.55 .44 .38 .24]);

% Setup button for analysing model:
st.h.model.analyse = uicontrol('style', 'pushbutton',...
    'units', 'normalized',...
    'position', [.55 .75 .1 .05],...
    'string', 'Analyse Model',...
    'callback', 'buildModel');

% Setup button for analysing model:
st.h.model.save = uicontrol('style', 'pushbutton',...
    'units', 'normalized',...
    'position', [.67 .75 .12 .05],...
    'string', 'Save simulated data',...
    'callback', 'disp(''Site under construction'')');

% Calculating the model:
runModel

% Updating all the figures:
icashow

